name: Monthly Data Update

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

# Add permissions needed for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Define workflow jobs
jobs:
  parse-data:
    name: 📊 Parse Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create cache directory
        run: mkdir -p cache

      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Parse EUR-Lex data
        run: |
          python parse_legal_acts_statistics.py --input "https://eur-lex.europa.eu/export-statistics-all.html?callingUrl=%2Fstatistics%2Flegislative-acts-statistics.html&statisticsType=LEGISLATIVE_ACTS" --output "cache/eurlex_legal_acts_statistics_${{ steps.date.outputs.current_date }}.csv" ${{ secrets